name: LaurenMcCabe
favicon: null
layout_spectrum: 0.7564989970996976
typography_spectrum: 0.4124614675529301
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.09848770825192332
  lightness: 0.6441561004612595
  saturation: 0.5763981649652123
  rhythmicContrast: 0.471811649389565
purpose: []
